<?php

  date_default_timezone_set('Europe/Rome');
  session_start();

  define('ENV', (($_SERVER['HTTP_HOST'] == 'www.mandadream.com') ? 'production' : 'development'));

  require("lib/class.phpmailer.php");
  require("lib/formvalidator.php");

  $config = array(
    'production' => array(
      'booking_email_address' => 'mandadreamkenya@gmail.com',
      'use_smtp' => false,
      'smtp_host' => '',
      'smtp_port' => 25
    ),
    'development' => array(
      'booking_email_address' => 'vin.aci@gmail.com',
      'use_smtp' => true,
      'smtp_host' => 'smtp.cayenne.it',
      'smtp_port' => 25
    )
  );

  function check_fields() {
    $errors = array();

    $validator = new FormValidator();

    # $validator->addValidation("first_name","req", "");
    # $validator->addValidation("last_name","req", "");
    $validator->addValidation("email", "req", "");
    $validator->addValidation("email", "email", "");
    # $validator->addValidation("phone", "req", "");
    # $validator->addValidation("arrival_date", "req", "");
    # $validator->addValidation("nights", "req", "");
    # $validator->addValidation("people", "req", "");
    # $validator->addValidation("from_country", "req", "");

    if (!$validator->ValidateForm()) {
      foreach($validator->GetErrors() as $input_name => $input_error) {
        array_push($errors, $input_name);
      }
    }

    return $errors;
  }

  $errors = check_fields();

  if (count($errors) > 0) {
    $_SESSION['fields_with_errors'] = json_encode($errors);
    die(header('Location: form-booking-warning.php'));
  }

  $labels = array(
    'first_name'   => "First name",
    'last_name'    => "Last name",
    'email'        => "Email",
    'phone'        => "Phone",
    'arrival_date' => "Arrival date",
    'nights'       => "Nights",
    'people'       => "People",
    'from_country' => "From country",
    'notes'        => "Notes",
    'newsletter'   => "Newsletter subscription",
  );

  $provided_fields = array();

  foreach ($_REQUEST as $key => $value) {
    if ($value) { array_push($provided_fields, "<li><b>{$labels[$key]}</b>: {$value}</li>"); }
  }

  $details = "<ul>" . join('', $provided_fields) . "</ul>";

  $booking_mail = new PHPMailer();

  if ($config[ENV]['use_smtp']) {
    $booking_mail->IsSMTP();
    $booking_mail->Host = $config[ENV]['smtp_host'];
    $booking_mail->Port = $config[ENV]['smtp_port'];
  }

  $booking_mail->AddAddress($config[ENV]['booking_email_address']);
  $booking_mail->SetFrom("{$_REQUEST['first_name']} {$_REQUEST['last_name']}", $_REQUEST['email']);
  $booking_mail->IsHTML(true);

  $booking_mail->Subject = "[ Mandadream ] New booking";
  $booking_mail->Body    = <<<HTML
    <p>A new booking was made through the <b>Mandadream</b> website.</p> <p>Details provided follows:</p>

    {$details}
    <p>This is an automatic message generated by <a href="http://www.mandadream.it">Mandadream</a> web site.

HTML;

  $thankyou_mail = new PHPMailer();

  if ($config[ENV]['use_smtp']) {
    $thankyou_mail->IsSMTP();
    $thankyou_mail->Host = $config[ENV]['smtp_host'];
    $thankyou_mail->Port = $config[ENV]['smtp_port'];
  }

  $thankyou_mail->AddAddress($_REQUEST['email']);
  $thankyou_mail->SetFrom("Mandadream", $config[ENV]['booking_email_address']);
  $thankyou_mail->IsHTML(true);

  $thankyou_mail->Subject = "[ Mandadream ] Booking confirmed";
  $thankyou_mail->Body    = <<<HTML
    <p>Kind {$_REQUEST['first_name']} {$_REQUEST['last_name']}, we would like to thank you for your booking on Mandadream.</p> <p>These are the details you provided:</p>

    {$details}
    <p>Thanks again from the <a href="http://www.mandadream.it">Mandadream</a> Staff.
HTML;

  if ($booking_mail->Send()) {
    $thankyou_mail->Send();
    header('Location: form-booking-success.html');
  } else {
    header('Location: form-booking-warning.php');
  }
